### ISSUE TITLE
php openssl_pkey_new() doesn't work on windows

### ISSUE THREAD

**Issue by awohsen** [TadavomnisT/SeRCH#3]
https://github.com/TadavomnisT/SeRCH/blob/96de54e80981f137f32809aea4a07a36213d1ca1/development_test_of_serch/serch_demo.php#L35
This function is executed here without catching its failure scenarios.

For better referencing in my case, the result of `openssl_error_string()` is:
`error:02001003:system library:fopen:No such processCant create session private key!`

However, it's easy to fix by providing a path to `openssl.conf ` manually like this: 
```php
if ($_ENV["OPENSSL_CONF"]){
    $this->private_key = openssl_pkey_new([
    "config" => $_ENV["OPENSSL_CONF"] //path to openssl.cnf
    ]);
}
```

So the final block could be like this: 
```php
$key_options = [
    "private_key_bits" => 2048,
    "private_key_type" => OPENSSL_KEYTYPE_RSA,
];

if ($_ENV["OPENSSL_CONF"]) $key_options["config"] = $_ENV["OPENSSL_CONF"]; //path to openssl.cnf

$this->private_key = openssl_pkey_new($key_options);
if (!$this->private_key) {
    print_r(openssl_error_string());
    die("Cant create session key pairs!");
}

if (!openssl_pkey_export($this->private_key, $private_key_pem, null, $key_options)){
    print_r(openssl_error_string());
    die("Cant create session key pairs!");
}
```

**Comment by TadavomnisT** [comment]
@awohsen 

ThanQ for reporting this issue, but this is just a test...A test of usability of RSA public key , with OpenSSL on php...

We got other bugs too....
The prompt_silent() function , is not working on every Unix-like system nor every windows version...

So fixing this(#3) will be the least of my priorities... but hey! feel free to open a PR , I'll merge it...

____________________________

One more thing...
I presume you are **"pico"** ... right? I begged you to message me, you bloody idiot!
I lost your fuckin contact info... due some recent assholic movements of you...


Please urgently contact me at `t.me/TadavomnisT` , I'm waiting...

**Comment by awohsen** [comment]
You can check out [Symfony solution ](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Console/Helper/QuestionHelper.php#L395-L448) for turning off echoing for the terminal and also windows.

I'm trying to rewrite the whole thing using PHP packages and etc; since you were not using them I guessed you don't like making things complicated so I preferred to just make an issue. 

also, there were not many helpful search results, so this would be better for people stuck with my situation as well.

```php
private function getHiddenResponse(OutputInterface $output, $inputStream, bool $trimmable = true): string
{
    if ('\\' === \DIRECTORY_SEPARATOR) {
        $exe = __DIR__.'/../Resources/bin/hiddeninput.exe';

        // handle code running from a phar
        if (str_starts_with(__FILE__, 'phar:')) {
            $tmpExe = sys_get_temp_dir().'/hiddeninput.exe';
            copy($exe, $tmpExe);
            $exe = $tmpExe;
        }

        $sExec = shell_exec('"'.$exe.'"');
        $value = $trimmable ? rtrim($sExec) : $sExec;
        $output->writeln('');

        if (isset($tmpExe)) {
            unlink($tmpExe);
        }

        return $value;
    }

    if (self::$stty && Terminal::hasSttyAvailable()) {
        $sttyMode = shell_exec('stty -g');
        shell_exec('stty -echo');
    } elseif ($this->isInteractiveInput($inputStream)) {
        throw new RuntimeException('Unable to hide the response.');
    }

    $value = fgets($inputStream, 4096);

    if (self::$stty && Terminal::hasSttyAvailable()) {
        shell_exec('stty '.$sttyMode);
    }

    if (false === $value) {
        throw new MissingInputException('Aborted.');
    }
    if ($trimmable) {
        $value = trim($value);
    }
    $output->writeln('');

    return $value;
}
```

For windows, it uses [this binary](https://github.com/Seldaek/hidden-input/blob/master/src/hiddeninput.cpp): 

```cpp
int main()
{
    HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE); 
    DWORD mode = 0;
    GetConsoleMode(hStdin, &mode);
    SetConsoleMode(hStdin, mode & (~ENABLE_ECHO_INPUT));

    string s;
    getline(cin, s);

    cout << s << endl;
    return 0;
}
```

**Comment by TadavomnisT** [comment]
@awohsen 

> ```CPP
> int main()
> {
>     HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE); 
>     DWORD mode = 0;
>     GetConsoleMode(hStdin, &mode);
>     SetConsoleMode(hStdin, mode & (~ENABLE_ECHO_INPUT));
> 
>     string s;
>     getline(cin, s);
> 
>     cout << s << endl;
>     return 0;
> }
> ```

but this is c++...
Not gonna do any help in php I think...
_________________________________________

Listen ... I refuse to continue this crap anymore, since you blocked me*-*
So you can go fuck yourself <3
Unless you message me OC...

**Comment by TadavomnisT** [comment]
[*] Not completed

**Comment by TadavomnisT** [comment]
@awohsen 
Supplied your approach 5f265c4, but it didn't take:

```
PHP Notice:  Undefined index: OPENSSL_CONF in C:\Users\user\Desktop\serch_demo.php on line 37

Notice: Undefined index: OPENSSL_CONF in C:\Users\user\Desktop\serch_demo.php on line 37
error:02001003:system library:fopen:No such processCant create session key pairs!
C:\Users\user\Desktop>
```

and I'm not a typical windows user, so basically maintaining programs on windows will cost me a life time.
Lemme know if you fixed it - issue remains open.

**Comment by awohsen** [comment]
Sorry for the late reply, usually I use https://github.com/vlucas/phpdotenv and .env file and I'm not sure how the environment variables and PHP work in windows but its fine with phpdotenv. 

https://github.com/TadavomnisT/SeRCH/commit/5f265c4fd946702f9bab895c40fbcfbaaef55489#diff-7681b3059ef76e8646ce145a8219c1cbb0c2d8fe9cf8ee0d89c1b823b98e3961R40
This line should've been like this to avoid notice my bad:
```php
if (isset($_ENV["OPENSSL_CONF"]))
```

`error:02001003:system library:fopen:No such processCant create session key pairs!`
It also looks like this could be fixed by `choco install openssl` in Windows and getting the latest OpenSSL version on Linux with no need for https://github.com/TadavomnisT/SeRCH/commit/5f265c4fd946702f9bab895c40fbcfbaaef55489
